name: Release Image in Flock Cloud
# Goal: tag and release an image that can be deployed 
# in flocksafety/flock-tunnel-proxy

on:
  workflow_dispatch:
  push:
    branches:
      - flock-main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  id-token: write
  actions: read

jobs:
  publish-tag:
    runs-on: ubuntu-latest
    name: Tag and Release
    outputs:
      tag: ${{ steps.cut-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version
        id: cut-version
        uses: flocksafety/flock-github-actions/cut-version@master

  docker-build:
    name: Docker Image
    needs: [publish-tag]
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.docker-build.outputs.digest }}
    steps:
      - uses: flocksafety/flock-github-actions/docker-build@master
        id: docker-build
        with:
          aws-role: arn:aws:iam::380235110861:role/flock-tunnel-proxy-github-oidc-role
          aws-ecr: 380235110861.dkr.ecr.us-east-1.amazonaws.com/flock-tunnel-proxy
          aws-region: us-east-1
          tags: ${{ needs.publish-tag.outputs.tag }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.FLOCK_NULL_RO_GITHUB_TOKEN }}
